# Uncomment the next line to define a global platform for your project
#platform :ios, '15.0'

target 'courtside' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Auth', '~> 9.0.0'
  pod 'Firebase/Firestore', '~> 9.0.0'
  pod 'Firebase/Core', '~> 9.0.0'
  pod 'FirebaseFirestoreSwift', '~> 9.0.0'
  # Pods for courtside
  pod 'Roboflow'

  pod 'nanopb', '~> 2.30908.0' 
  target 'courtsideTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'courtsideUITests' do
    # Pods for testing
  end

end
